version: '3'

services:
  wordpress:
    build: .
    ports:
      - "${APACHE_PORT:-8001}:80"
      - "${APACHE_PORT_SSL:-8002}:443"
    volumes:
      - ./wordpress:/var/www/html
      - ./apache/php.ini:/usr/local/etc/php/php.ini
      - ./apache/httpd-limits.conf:/etc/apache2/conf-available/httpd-limits.conf